CREATE TABLE IF NOT EXISTS prison (
  jid INT PRIMARY KEY NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  reference VARCHAR(36) NOT NULL,
  properties TEXT NOT NULL,
  status VARCHAR(10) NOT NULL
);

