CREATE TABLE IF NOT EXISTS images (
  id  VARCHAR(36) PRIMARY KEY NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  hash VARCHAR(64) NOT NULL,
  host TEXT NOT NULL,
  manifest TEXT NOT NULL,
  timestamp DATETIME NOT NULL,
  
);

