#ifndef __DAEMON_DOMAIN_CONTAINERS_FREEBSD_INTERNAL_UTILS__
#define __DAEMON_DOMAIN_CONTAINERS_FREEBSD_INTERNAL_UTILS__
namespace domain::containers::freebsd
{

}

#endif // __DAEMON_DOMAIN_CONTAINERS_FREEBSD_INTERNAL_UTILS__