containers:
    path: '/home/william/voltron/containers'
database:
    path: '/home/william/voltron/data/voltron.db'
    pool-size: 10
images:
    path: '/home/william/voltron/images'
networking:
    ip-v4-cidr: '172.23.0.1/16'
    ip-v6-cidr: '2001:db8:1::/64'
domain-socket: '/home/william/Projects/demonstration/unix.socket.jpod'
