containers:
    path: '/home/william/jpod/storage/containers'
database:
    path: '/home/william/jpod/data/jpod.db'
    pool-size: 10
images:
    path: '/home/william/jpod/storage/images'
networking:
    ip-v4-cidr: '172.23.0.1/16'
    ip-v6-cidr: '2001:db8:1::/64'
