containers:
    path: '/home/william/voltron/containers'
database:
    path: '/home/william/voltron/data/voltron.db'
    pool-size: 10
images:
    path: '/home/william/voltron/images'
volumes:
    path: '/home/william/voltron/volumes'
networking:
    ip-v4-cidr: '172.23.0.1/16'
    ip-v6-cidr: 'fd12:3456:789a:1::/64'
    bridge: jc0
domain-socket: '/home/william/Projects/updates/unix.socket.jpod'
